name: book_finder
description: A simple book finding app

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  url_launcher: ^4.0.1
  shared_preferences: ^0.4.3
  rxdart: ^0.18.1

flutter:
  uses-material-design: true